### PR TITLE
Change Cxx standard -std=... to compile feature

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
This extracts the -std=c++xx flags from the cflags of pkgconfig and plain packages(and similar) and turns them into compile_features.

This improves the cases where multiple different -std=c++ flags are defined so that the highest standard(by cmakes definition) is used instead of the one that happens to be introduced by the last mentioned dependency.

This does not handle std=gnu++xx well because it cannot be converted to cmakes compile_feature cleanly.

This fixes the case where previously, the build of a package would fail because one of its dependencies would require -std=c++14 (ex: pcl), and one requires -std=c++11(on ubuntu 18.04, basically everything), and they are mentioned in this order in the rock_library call.

This is related to similar work done for orogen: https://github.com/rock-core/tools-orogen/pull/11

### CODE REVIEW

**Comment by pierrewillenbrockdfki** [comment]
@doudou you asked for testcases to be added to https://github.com/rock-core/rock.build-tests-buildconf , how do we go about adding them in rock-core?

That would be an extension of https://github.com/rock-core/build_tests-cmake-plain_cxx11_package (to have a library that requires at least c++11), and addition of `build_tests/cmake/plain_cxx14_package`, `build_tests/cmake/cxx_standards_11_then_14`, `build_tests/cmake/cxx_standards_14_then_11`, and for the orogen side `build_tests/orogen/cxx_standards_11_then_14`, `build_tests/orogen/cxx_standards_14_then_11`

Easiest way would probably be to add me to the rock-core members.

**Comment by doudou** [comment]
> Easiest way would probably be to add me to the rock-core members.

Done.

**Comment by pierrewillenbrockdfki** [comment]
> > Easiest way would probably be to add me to the rock-core members.
> 
> Done.

@doudou 

Thank you.

So, i added test cases, the ones currently failing are commented out in the [PR](https://github.com/rock-core/rock.build-tests-buildconf/pull/19) for the build-conf. One [PR](https://github.com/rock-core/build_tests-cmake-plain_cxx11_package/pull/1) that could be done already for the "at least c++11" library that is used by the tests. I can also do that one as a separate package, but i only need the library, so i put it in the same package as the other c++11 library.

Want me to go ahead and just merge these, or do you want to take a look first?

**Comment by pierrewillenbrockdfki** [comment]
@doudou Everything for the testcases is setup; should i go ahead and merge this and update the testing buildconf to test the cmake bits?

**Comment by doudou** [comment]
Yes !

**Comment by pierrewillenbrockdfki** [comment]
@doudou finally found some time to do the merges and update the testing build conf. I think this sorts the cmake bits. I'll now take another look at the orogen bits and possibly ask questions/for review over there.

**Pull request merged**
