### PR TITLE
Use legacy alias in get_filename_component to allow usage with older …

### PR DESCRIPTION
**Pull request by 2maz**
…CMake versions

http://www.cmake.org/cmake/help/v3.0/command/get_filename_component.html

### CODE REVIEW

**Comment by doudou** [comment]
It's simple enough I guess ... but do we really want to keep backward compatibility on master for pre-14.04 Ubuntus ? (14.04 had cmake 2.12 already). It still means that at some point down the file it will fail and we'll have to change it back ...

**Comment by 2maz** [comment]
Low-hanging fruit to keep the macros downward compatible -- even though we might not support the full bootstrap for pre-14.04. Changing it back or 'upgrading' would only be necessary if the alias is removed!?
Btw. we are not requiring a minimum version of cmake for the macros and there is another occurrence of get_component using PATH -- so it makes the macros more consistent.

**Comment by doudou** [comment]
> Low-hanging fruit to keep the macros downward compatible

Agreed, but at the cost of having trouble later on (we'll have to basically "upgrade" in a hurry the time CMake removes the backward-compatible alias). However, if it is already used with PATH elsewhere, that's fair enough indeed.

>  we are not requiring a minimum version of cmake

We definitely should.... If that's possible I seem to remember that cmake_minimum_required has to be the very first thing called.

Anyways, not related to this PR. I merge.

**Comment by doudou** [comment]
Opened an issue for the version requirement (#23)

**Pull request merged**
