### PR TITLE
update FindBoost to version of CMake 2.8.12

### PR DESCRIPTION
**Pull request by jmachowinski**
There is a bug in the old version, that introduces
optional and debug into the linker flags

### CODE REVIEW

**Comment by jmachowinski** [comment]
In general, we should delete our findBoost.cmake As CMake > 2.8 has it, there is no point in maintaining our own version

**Comment by doudou** [comment]
Agreed. The only thing I could find within the git history about FindBoost is a mention of a bug reported by @2maz, which seems to be fixed https://gitlab.kitware.com/cmake/cmake/issues/12205

**Comment by 2maz** [comment]
+1 for removal

**Comment by jmachowinski** [comment]
Okay, then I merge this now, wait 2 weeks and remove the file then.
The idea is that the fixed version settles into existing installations,
and on the next full bootstrap the system version is used.

**Pull request merged**
