### PR TITLE
Account for header only libraries in rock_prepare_pkgconfig

### PR DESCRIPTION
**Pull request by 2maz**
Fix #43 assumption on existing library target

### CODE REVIEW

**Comment by jmachowinski** [comment]
gui/osgviz/osgviz builds now.
But base/numerics fails to compile

**Comment by 2maz** [comment]
Update this PR and added second: rock-core/base-numeric#18

**Comment by doudou** [comment]
I've changed this PR base after the merge of #46. Pushed the original PR state (before revert) to the export_cxx11_in_pkgconfig_files branch for testing.

**Comment by doudou** [comment]
This fixes the [build tests](https://github.com/rock-core/base-cmake/pull/43#issuecomment-318380602) I've added for the header-only packages, in both C++11 and non-C++-11 cases. I merge.

**Pull request merged**
