### PR TITLE
remove FindRuby.cmake

### PR DESCRIPTION
**Pull request by doudou**
The version shipped with recent CMake fixes the main issue that
led to this inclusion (RbConfig vs. Config), and fixes many more
problems as well (as e.g. executable name)

Closes #7

### CODE REVIEW

**Comment by doudou** [comment]
This would require testing on more than one machine/OS ...

**Comment by 2maz** [comment]
What minimum version of CMake is required for that to work?

**Comment by goldhoorn** [comment]
Seriosly, you even not tried this PR on your machine?

```
autoproj: importing and loading selected packages
autoproj: building and installing packages
Command failed                     
base/cmake(/home/goldhoorn/bootstraps/min/dev/base/cmake): failed in install phase
    'make -j6 install' returned status 2
    see /home/goldhoorn/bootstraps/min/dev/install/log/base/cmake-install.log for details
    last 10 lines are:

    -- Up-to-date: /home/goldhoorn/bootstraps/min/dev/install/share/rock/cmake/FindBoost.cmake
    -- Up-to-date: /home/goldhoorn/bootstraps/min/dev/install/share/rock/cmake/FindGem.cmake
    -- Up-to-date: /home/goldhoorn/bootstraps/min/dev/install/share/rock/cmake/FindNumpy.cmake
    CMake Error at cmake_install.cmake:36 (file):
      file INSTALL cannot find
      "/home/goldhoorn/bootstraps/min/dev/base/cmake/modules/FindRuby.cmake".
    
    
    Makefile:66: recipe for target 'install' failed
    make: *** [install] Error 1
```

**Comment by doudou** [comment]
> What minimum version of CMake is required for that to work?

No idea. I only have had a look at FindRuby on 3.0. You know, that's also what "cooperative development" means. If nobody wants to, then this can linger forever here for all I care.

> Seriosly, you even not tried this PR on your machine?

Actually, I did .... but forgot to commit half of it :( Sorry.

**Comment by doudou** [comment]
> Seriosly, you even not tried this PR on your machine?

Well, I *thought* I forgot to commit half of it. What happened is that autoproj does not detect a change if the only thing you do is remove a file (because timestamps don't change then). So, it built just fine ...

Updated with relevant change on the cmake code.

And, for the record, one usually uses a little less toned down attitude when speaking to the only person that spends 1/3 of its time reviewing the usually more than 50% crappy PRs. And keeps it (mostly) civil. When trivial PRs on the package sets are just sitting there for weeks, that's not on me.

**Comment by goldhoorn** [comment]
Builds rock-base master on debian stable/testing (mixed) with cmake 3.0.2-1 without any problems.

**Comment by doudou** [comment]
> Builds rock-base master on debian stable/testing

Great. I am more concerned about 14.04 I have to admit ...

**Comment by goldhoorn** [comment]
Failing on Ubuntu 14.04.3 log:
```

2015-08-26 10:10:32 +0200: running
    cmake -DCMAKE_INSTALL_PREFIX=/home/goldhoorn/dev/install -DCMAKE_MODULE_PATH= -DCMAKE_BUILD_TYPE=Debug -DROCK_TEST_ENABLED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/goldhoorn/dev/tools/orogen_metadata
with environment:
  'AUTOPROJ_CURRENT_ROOT'='/home/goldhoorn/dev'
  'CMAKE_PREFIX_PATH'='/home/goldhoorn/dev/install'
  'GEM_HOME'='/home/goldhoorn/dev/.gems'
  'GEM_PATH'='/home/goldhoorn/dev/.gems:/home/goldhoorn/.gem/ruby/2.0.0:/var/lib/gems/2.0.0:/usr/share/rubygems-integration/2.0.0:/usr/share/rubygems-integration/all'
  'HOME'='/home/goldhoorn'
  'LANG'='de_DE.UTF-8'
  'LD_LIBRARY_PATH'='/home/goldhoorn/dev/install/lib'
  'LESSCLOSE'='/usr/bin/lesspipe %s %s'
  'LESSOPEN'='| /usr/bin/lesspipe %s'
  'LOGNAME'='goldhoorn'
  'LS_COLORS'='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:'
  'MAIL'='/var/mail/goldhoorn'
  'OLDPWD'='/home/goldhoorn'
  'ORBInitRef'='NameService=corbaname::127.0.0.1'
  'OROCOS_TARGET'='gnulinux'
  'OROGEN_PLUGIN_PATH'='/home/goldhoorn/dev/install/share/orogen/plugins'
  'OSG_FILE_PATH'='/home/goldhoorn/dev/install/share/vizkit'
  'PATH'='/home/goldhoorn/dev/tools/metaruby/bin:/home/goldhoorn/dev/tools/orogen/bin:/home/goldhoorn/dev/tools/log_tools/bin:/home/goldhoorn/dev/tools/roby/bin:/home/goldhoorn/dev/tools/pocolog/bin:/home/goldhoorn/dev/tools/orocos.rb/bin:/home/goldhoorn/dev/tools/syskit/bin:/home/goldhoorn/dev/base/scripts/bin:/home/goldhoorn/dev/tools/rubigen/bin:/home/goldhoorn/dev/gui/vizkit/bin:/home/goldhoorn/dev/tools/telemetry/bin:/home/goldhoorn/dev/tools/rest_api/bin:/home/goldhoorn/dev/install/bin:/home/goldhoorn/dev/.gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
  'PKG_CONFIG_PATH'='/home/goldhoorn/dev/install/lib/pkgconfig:/home/goldhoorn/dev/install/lib64/pkgconfig'
  'PWD'='/home/goldhoorn/dev'
  'PYTHONPATH'=''
  'PYTHONUSERBASE'='/home/goldhoorn/dev/.pip'
  'QT_PLUGIN_PATH'='/home/goldhoorn/dev/install/lib/qt'
  'QT_QPA_PLATFORMTHEME'='appmenu-qt5'
  'ROBY_PLUGIN_PATH'='/home/goldhoorn/dev/tools/syskit/lib/syskit/roby_app/register_plugin.rb:/home/goldhoorn/dev/base/scripts/lib/rock/roby_plugin.rb'
  'ROCK_BUNDLE_PATH'='/home/goldhoorn/dev/bundles:/home/goldhoorn/dev/install/share/rock'
  'ROCK_PREFIX'='/home/goldhoorn/dev/install/share/rock'
  'ROCK_TEMPLATE_PREFIX'='/home/goldhoorn/dev/base/templates/'
  'ROCK_TEMPLATE_SUFFIX'=''
  'ROCK_WEBAPP'='/home/goldhoorn/dev/install/share/rest_api'
  'RUBYLIB'='/home/goldhoorn/dev/tools/metaruby/lib:/home/goldhoorn/dev/tools/utilrb/lib:/home/goldhoorn/dev/tools/orogen/lib:/home/goldhoorn/dev/tools/log_tools/lib:/home/goldhoorn/dev/tools/roby/lib:/home/goldhoorn/dev/tools/pocolog/lib:/home/goldhoorn/dev/tools/orocos.rb/lib:/home/goldhoorn/dev/tools/syskit/lib:/home/goldhoorn/dev/base/scripts/lib:/home/goldhoorn/dev/tools/rubigen/lib:/home/goldhoorn/dev/gui/vizkit/lib:/home/goldhoorn/dev/tools/telemetry/lib:/home/goldhoorn/dev/tools/rest_api/lib:/home/goldhoorn/dev/install/lib/x86_64-linux-gnu/ruby/2.0.0:/home/goldhoorn/dev/install/lib/ruby/2.0.0:/home/goldhoorn/dev/slam/envire/ruby:/home/goldhoorn/dev/drivers/transformer/ruby/lib'
  'RUBYOPT'='-rubygems'
  'SHELL'='/bin/bash'
  'SHLVL'='1'
  'SSH_CLIENT'='10.250.3.125 32835 22'
  'SSH_CONNECTION'='10.250.3.125 32835 10.250.5.12 22'
  'SSH_TTY'='/dev/pts/0'
  'TERM'='xterm'
  'TYPELIB_RUBY_PLUGIN_PATH'='/home/goldhoorn/dev/install/share/typelib/ruby'
  'USER'='goldhoorn'
  'VIZKIT_PLUGIN_RUBY_PATH'='/home/goldhoorn/dev/install/lib/vizkit:/home/goldhoorn/dev/install/lib'
  'XDG_RUNTIME_DIR'='/run/user/1000'
  'XDG_SESSION_ID'='1'
  '_'='/home/goldhoorn/dev/.gems/bin/autoproj'

2015-08-26 10:10:32 +0200: running
    cmake -DCMAKE_INSTALL_PREFIX=/home/goldhoorn/dev/install -DCMAKE_MODULE_PATH= -DCMAKE_BUILD_TYPE=Debug -DROCK_TEST_ENABLED=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON /home/goldhoorn/dev/tools/orogen_metadata
in directory /home/goldhoorn/dev/tools/orogen_metadata/build
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Performing Test CXX_SUPPORTS_Wall
-- Performing Test CXX_SUPPORTS_Wall - Success
-- Performing Test CXX_SUPPORTS_Wno_unused_local_typedefs
-- Performing Test CXX_SUPPORTS_Wno_unused_local_typedefs - Success
-- Performing Test CXX_SUPPORTS_Wnon_virtual_dtor
-- Performing Test CXX_SUPPORTS_Wnon_virtual_dtor - Success
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Export include dir: '/home/goldhoorn/dev/tools/orogen_metadata/build/include/_orogen_metadata_/orogen_metadata' already exists
-- Could NOT find Ruby (missing:  RUBY_CONFIG_INCLUDE_DIR) (found version "2.0.0")
-- did not find Yard, the Ruby packages won't generate documentation
-- Ruby library not found. Skipping Ruby parts for this package
-- Ruby library not found. Cannot build Ruby extensions
CMake Error at CMakeLists.txt:6 (rock_ruby_library):
  Unknown CMake command "rock_ruby_library".


-- Configuring incomplete, errors occurred!
See also "/home/goldhoorn/dev/tools/orogen_metadata/build/CMakeFiles/CMakeOutput.log".
```

**Comment by doudou** [comment]
It's actually weird that it worked with our FindRuby

Anyways, this would be fixed by adding the RUBY_EXECUTABLE define the same way we did for the other ruby-based packages (and, incidentally, would make sure that orogen_metadata works fine on systems where multiple ruby binaries are present)

**Comment by 2maz** [comment]
Looks like RUBY_FOUND ist not properly set with the the default FindRuby.cmake, and RUBY_LIBRARY_INSTALL_DIR is also not set so that RockRuby.cmake does not work anymore -- maybe there is even more -- just traced it to that point

**Comment by doudou** [comment]
Some update on that: the current version seem problematic on MacOS (orocos-toolchain/typelib#98 (comment))

**Comment by doudou** [comment]
At least for me Rock Core builds fine with the stock file ...

**Pull request closed without merging**
