### PR TITLE
Remove current-directory-global target settings coming from dependencies

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
This removes the include_directories and add_definitions calls that are generated by rock_library etc. for the DEP* arguments and replaces them with target_include_directories, target_compile_definitions and target_compile_options. The link_directories were kept; target_link_directories is a more recent addition and is not as problematic as include_directories.

Compile-testing(142 packages) showed one instance where a target failed to declare its dependencies and missed an include after this change (https://github.com/rock-cpp/rtt_introspection/blob/d4b3f216b309e86bbac2fb24dc2bb6f4c7d4c4d4/src/CMakeLists.txt#L20; missing `orocos-rtt-${OROCOS_TARGET}`; this will be fixed in any case)

I think this is a cleaner approach to include directories, options and definitions and keeps the more global namespaces from being polluted, avoiding strange cross-target dependencies, also cases where a certain target order must be kept without actually mentioning a dependency between them.

@doudou what do you think? Also, a close review is appreciated; it is very possible i missed some cmake idioms, conventions and pitfalls.

This is work towards having qt4 and qt5 libraries and executables built at the same time in the same project. A fully working version of this patchset, but with additional changes required for the qt5 parts, can be found in https://github.com/pierrewillenbrockdfki/base-cmake/tree/mixed-build-qt4-qt5. Two more things that may be of interest can be found in https://github.com/pierrewillenbrockdfki/base-cmake/tree/wip-qt5, especially https://github.com/pierrewillenbrockdfki/base-cmake/commit/12ace1dcd6a5bbdcb4987591529c311338cef019

### CODE REVIEW

**Comment by doudou** [comment]
I like the idea very much.

What I currently pepper code with are exactly this kind of feature flags, but with a message that says "you are using behavior XXX, it is deprecated, call `rock_features(NOCURDIR)` just after `rock_init` to switch to the new behavior. The default behavior will be changed in the future.`

**Comment by pierrewillenbrockdfki** [comment]
Added rock_feature, made it change the behavior to switch between applying definitions and include_directories in directory scope vs in target scope. Dropped the changes to rock_find_qt4 argument parsing. @doudou , what do you think?

**Review by doudou — APPROVED** [review]

**Comment by doudou** [comment]
Great stuff !

**Comment by doudou** [comment]
Can you merge it ? Or should I ?

**Comment by pierrewillenbrockdfki** [comment]
@doudou  No, i cannot merge this, please go ahead. Next, i will pull the c++ standard change out of the qt work. This will impact this repo as well and works well with this MR.

**Pull request merged**
