### PR TITLE
Add handling of corner case for library python2.7

### PR DESCRIPTION
**Pull request by 2maz**
Currently a library path libpython2.7.so will end up as -lpython2 in the pkgconfig file, while it should be -lpython2.7

Patch is probably insufficient with respect to Mac ....

### CODE REVIEW

**Comment by doudou** [comment]
Isn't there a way to get the local "solib" file extension in CMake ?

**Comment by 2maz** [comment]
Could not find any function for it, but only the variables defined in Modules/CMakeGenericSystem.cmake.
Thus, tried make the name extraction a bit more generic, i.e. platform independent.

**Comment by 2maz** [comment]
ping

**Comment by doudou** [comment]
Looks good.

**Pull request merged**
