### PR TITLE
Added macro for CXX11 activation (not enabled by default (so far))

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
Regarding the discussion in https://github.com/rock-planning/planning-pddl_planner/pull/1#issuecomment-75241181 pushed option to enable cxx11 from CMake Define

**Comment by doudou** [comment]
@goldhoorn: I would actually recommend adding that to the discussion Leif started on the ML a month or two ago

**Comment by D-Alex** [comment]
Mixing libraries compiled with different compiler options (C++0x etc). is asking for trouble. I would rather upgrade autoproj to set the flag for the hole installation.

**Comment by goldhoorn** [comment]
As discussed on the Rock-video meeting i merge

**Pull request merged**
