### PR TITLE
use stock FindBoost

### PR DESCRIPTION
**Pull request by doudou**
[The original reason](https://github.com/rock-core/base-types/commit/1717949) why we had our own has seem to have been fixed since (https://gitlab.kitware.com/cmake/cmake/issues/12205).

@2maz do you have a setup that could verify it is indeed fixed ?

### CODE REVIEW

**Comment by 2maz** [comment]
Currently I do not have one available, but I see if I can mock a setup.

**Comment by planthaber** [comment]
We starting to get issues with the Boost::unit_test_framework target, what is the reason that this is labelled [do-not-merge](https://github.com/rock-core/base-cmake/labels/do-not-merge)?

**Comment by chhtz** [comment]
After replacing `DEPS` by `DEPS_PLAIN` (see mentions above), `pkg-config --libs ${library_that_depends_on_boost}` does not list the boost libraries anymore (before this change, but after applying this patch, it added `Boost::something`-entries, which are of course not valid libs on the pkg-config level). 

Somehow, on my workspaces this seems not break anything, but I got a report from another user with undefined reference errors (things that would be solved if `pkg-config --libs` would return the corresponding libs). I'm investigating if they did something different.

**Comment by chhtz** [comment]
We have these changes applied in our institute and did not experience any problems for a while now.

@2maz @doudou @planthaber Shall we merge this?

**Review by 2maz — APPROVED** [review]
No objections.

**Pull request merged**
