### PR TITLE
fixed checking of linker options

### PR DESCRIPTION
**Pull request by malter**

### CODE REVIEW

**Comment by doudou** [comment]
This is adding the noexecstack non-conditionally. The whole point of testing for it is that some archs have the feature and some don't.

What was the issue you encountered in the first place ?

**Comment by malter** [comment]
The testing was not working, maybe because it is a linker option and not a compiler option. I found this hint how to check for linker options: http://www.cmake.org/pipermail/cmake/2011-July/045525.html

**Comment by goldhoorn** [comment]
In respect to the cmake ML i think its okay

**Comment by doudou** [comment]
Me too, feel free to merge

**Pull request merged**
