### PR TITLE
FindRuby: add "ruby1.9.1" to list of possible ruby-interpreter

### PR DESCRIPTION
**Pull request by marvin2k**
not sure if this is actually a good fix...

got this because "tools/orogen_metadata" didn't specify
"-DRUBY_EXECUTABLE=/usr/bin/ruby1.9.1" on the cmake-line (as _some_
projects do) and thus couldn't find any ruby-interpreter with the
current FindRuby.cmake -- hence this fix.

- wasn't there this executable file named "ruby" in the PATH, just
  calling the correct `/usr/bin/ruby1.9.1`, removing the need for any
  ruby-lookup?
- which is the preferred ruby-version? 1.9.1 (which is actually version
  1.9.3, as ruby1.9.1 reports on my Debian...) is quite old, 2.1.2 is
  there in the moment. I assume mixing is not possible...
- why do some projects give the ruby-interpreter to cmake already, and
  some not? non-consistent stuff is bound to break...

Signed-off-by: Martin Zenzes <martin.zenzes@dfki.de>

### CODE REVIEW

**Comment by goldhoorn** [comment]
Is still still a valid PR or can it be closed?

**Comment by marvin2k** [comment]
The pactch is not really relevant anymore... given that ruby 1.9.1 will probably be used less and less... But the underlying problem prevails ;-)

**Comment by goldhoorn** [comment]
1.9.1 is still  default for most of the rock installations

nevertheless i never encounter your problem:

```
[10:04:15 goldhoorn ~]$ ruby
ruby       ruby1.8    ruby1.9.1  ruby1.9.3  ruby2.0    ruby2.1
```

even with this setup everything works fine.


On 03.06.2015 09:57, marvin2k wrote:
>
> The pactch is not really relevant anymore... given that ruby 1.9.1 
> will probably be used less and less... But the underlying problem 
> prevails ;-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/base-cmake/pull/7#issuecomment-108236030>.
>


-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by doudou** [comment]
If anything, we should also add ruby 2.0 and 2.1 to the list.

re-reading the thread, there has been two parts in this discussion: 
 - the autodetection should NOT be used in Rock, because that is room for trouble. Every cmake package which require a ruby interpreter should have RUBY_EXECUTABLE explicitely set.
 - however, in general, fixing the autodetection should not hurt.

**Comment by goldhoorn** [comment]
@marvin2k : Since we decided today to drop ruby1.9.1 can you please rework your patch and only add 2.1 and 2.0 to this?

**Comment by marvin2k** [comment]
The way this Find-conundrum seems to be used by Rock is that the `Ruby_FIND_VERSION_MAJOR` and `RUBY_FIND_VERSION_MINOR` are preset to some values somewhere else? This is then used to construct the search-pattern for `find_program()` -- `ruby19` for example. But the peculiar fact that on the Debian system I had back then, the interpreter was called `ruby-1.9.1` led to the failing of the given script. I don't think just adding `ruby2.0`, `ruby20`, `ruby2.1`, and `ruby21` into the list would do us any good, since the hack in the PR was _just_ for this unfortunate naming in the `ruby-1.9.1` case.

Additionally, note that the `cmake-data` package of Debian Jesse and Ubuntu Trusty both ship a script named like this with more modernizations present. Instead of reinventing the (or maintaining a reinvented) wheel I propose to just use one of those -- either dropping our Find-script or just copying theirs. However, testing this is beyond my current scope...

**Comment by doudou** [comment]
@marvin2k: the selection is done by explicitely passing the ruby interpreter as RUBY_EXECUTABLE

I'm all for dropping handmade scripts like this, but that would require some testing, obviously.

**Comment by marvin2k** [comment]
If `RUBY_EXECUTABLE` is passed directly, all this script could do in autodetection of the interpreter is fucking it up?

**Comment by doudou** [comment]
Nope. find_program is a noop is RUBY_EXECUTABLE is set. The rest of the script extracts a lot of parameters.

**Comment by marvin2k** [comment]
Yes, I saw that extraction. But the autodetection (find_program in the end) can only make mistakes. So _we_ (contrary to Debian or Ubuntu) could remove this part.

**Comment by goldhoorn** [comment]
I close this because ruby1.9 is unsupported and there exists a new PR which removes this part of code completly

**Pull request closed without merging**
